### ISSUE TITLE
How many prompts did you needed to make the add-on, and how was the workflow?

### ISSUE THREAD

**Issue by moebiussurfing** [tettou771/ofxChatGPT#1]
Hey @tettou771 , thanks for sharing.

Do you have some guide about what prompts do you used to create the addon?
Too many steps and too much retries?

It could be nice to have some cool prompts to make some ofxAddons/wrappers for some cpp libs, for exmple.

Regards

**Comment by tettou771** [comment]
Hello,

First, please obtain your OpenAI API key. Once you have the key, you can input your key information in the setup() function found in the provided examples. Run the examples with your API key in place, and this should help you understand the prompts used, the steps involved, and how to effectively create ofxAddons/wrappers for C++ libraries.

If you have any questions or need further clarification, feel free to copy and paste the source code into ChatGPT. It should be able to provide you with useful answers and guidance.

Please don't hesitate to reach out if you have any additional questions or need further assistance.

Best regards,

**Comment by tettou771** [comment]
Hi @moebiussurfing 

I apologize for not fully understanding the content of your question earlier. 
When I created this add-on (the first version), I believe I used GPT-4 to generate 20-30 prompts. I also had it write most of the ofxChatGPT itself, and it was really helpful to have it create the README and example in an instant. However, when adding features later, I pasted the entire source code and had a conversation with GPT in a new thread, so I don't know exactly how many conversations I had.

At first, I didn't know how to implement the chatWithHistory feature, but ChatGPT was very knowledgeable about its own system, so I mostly just copied and pasted the code it provided. However, looking at it now, I feel like there's a lot of duplicate code, so I'm considering asking for some refactoring help (though I'm a little worried it might break something).

**Comment by tettou771** [comment]
When using GPT-3.5, I often encounter mistakes, which can be time-consuming, but with GPT-4, it feels like I'm being taught by a knowledgeable senior.

**Comment by moebiussurfing** [comment]
Thanks for the explanation, @tettou771 

(I am neither English language speaker, my main language is Spanish. So probably, many times I am not correct or enough clear when writing. It requires an extra effort and assistant correctors also by my side.)
